### ISSUE TITLE
Implement global header/footer design across w.org network

### ISSUE THREAD

**Issue by iandunn** [WordPress/wporg-mu-plugins#38]
After it's implemented for News in WordPress/wporg-news-2021#6, we'll need to roll the new header/footer out to all sites in the network. That can/should probably happen before News launches.

There are a lot of potential improvements we can make under the hood, to make the header easier to maintain across the various systems that implement it. It'd be nice to do at least some of that here, but we'll have to weigh the time/benefit tradeoffs for each one.

### Pain Points

> This file is used by wordpress.org static files including index-wporg.php. It is also used by the codex [and GlotPress, Trac, etc], based on a cron job set up to fetch header.php?wpcodex=1.
> 
> And, a lot of WordPress and bbPress themes include it.
> 
> Changes require global testing!

* It’s a pain to include the header in local environments, since you have to curl `w.org/header.php` instead of having a dynamic file. It's easier to fork it, but those quickly become out of date.
* Changes have to be manually copied to the hardcoded Genshi templates for Trac
* It’s hard to test updates to Trac and the Codex before deploying.
* Testing the changes across all sites is tedious, and it’s easy to miss something
* `wp4.css` is massive, and changes have unintended consequences
* footer strings have to be copied to `pub/wporg/footer.php` for localization

### Potential solutions

We could:

- [x] Open source the files. We should do this if nothing else. Maybe make the global header a separate repo with completely self-contained styles, or just commit to `meta.svn`
- [x] I think the styles would be easier to maintain, and less fragile, if they were component-ized in the new design, rather than remaining a part of the wp4.css maze. That could still be used by the other themes/systems until they’re migrated to the new parent. We could remove the header/footer styles from `wp4.css` and move them to some shareable component.
- [x] create a REST API endpoint to get the HTML for the header/footer. that seems like a more modern version of how some sites will `curl https://wordpress.org/header.php` to import it.
- [ ] To make global testing easier and more reliable, we could setup e2e screenshot comparisons or something. They might have to be post-deploy given the lack of dev environments for Trac etc, though.
- [x] Is there a reason Trac doesn’t `<iframe>` it, or curl-and-cache it like the Codex? Could the Codex `<iframe>` it for simplicity? probably because submenus/modals can't expand beyond fixed height of the iframe

### Refine existing code

- [x] #44 - high
- [x] #29  - high
- [x] #46 - high
- [x] #35 - high
- [x] #52 - high
- [x] #42 - medium
- [x] #22 - medium
- [x] #57 - medium
- [x] port any needed features from old `footer.php` - medium
- [x] test bbpress. need to call `bb_head()`, footer etc like is done for GlotPress?
- [x] https://github.com/WordPress/wporg-mu-plugins/issues/81
- [x] update hardcoded strings in Learn footer, or make it so that they're not necessary. at the very least, make them DRY across sites. this may be unnecessary after #46, or may be a post-launch thing

### Add new features

- [x] add feature flag on production so can commit progress but not have it loaded
- [x] output `wp_head()` in classic themes, but not FSE themes
- [x] #19
- [x] #49
- [x] #47
- [x] #48
- [x] migrate `/search/index.php` content to WP page and delete
- [x] #37 - high
- [x]  #67 - high
- [x] #50 - medium
- [x] #45 - medium
- [x] #53 - medium
- [x] #58 - low

### Launch day

Tracked in #100

### Post-launch iteration:

Tracked in #55

**Comment by iandunn** [comment]
Now that WordPress/wporg-news-2021#6 is done, it'd be a good time to start thinking about this. It's a big chunk of work that's essential to the launch.

@dd32, do you have any thoughts on any of it? Are there any parts you'd like to do?

**Comment by zackkrida** [comment]
Hi folks, chiming in to note that Openverse would also ideally use w.org/header.php and w.org/footer.php once they are updated. Inlined styles and scripts for these parts would be ideal for our use case. I'll keep an eye on things here and if details about our implementation would be useful just let me know.

**Comment by ryelle** [comment]
These items are unchecked and don't have corresponding issues:

> To make global testing easier and more reliable, we could setup e2e screenshot comparisons or something. They might have to be post-deploy given the lack of dev environments for Trac etc, though.

> port any needed features from old footer.php - medium

> update hardcoded strings in Learn footer, or make it so that they're not necessary. at the very least, make them DRY across sites. this may be unnecessary after internationalize new header/footer #46, or may be a post-launch thing

Are they still relevant? Are they needed for launch?

**Comment by iandunn** [comment]
I just checked off the last two after closing #46. The first was an aspirational thing, but I don't think it's worth it right now.

**Comment by fierevere** [comment]
thank you for completely breaking the UX for forums and translation system.
Very appreciated for making them unusable. Now i can see the global menu, everytime, instead of the content of the forum posts and translation strings. This is really important for all the contributors on the forums and the translators - PERMANENT ON SCREEN MENU!

Also on rosetta sites locale managers are unable to define custom menus, can only add extra items after global menus, 
NO LINKS CHANGING, NO SORTING.
Decisions, not options! Truly WordPress way.

**Comment by Otshelnik-Fm** [comment]
I have been translating Gutenberg into Russian for several years. Now you have killed the interface. I quit using this service and being active until you remove the huge menu and return the styling of the service interface.

**Comment by tellyworth** [comment]
Thanks for the feedback, and sorry this has caused issues for Translate! Do you mind posting some screenshots demonstrating the problems you're seeing? It seems that some of them are specific to particular screens and/or window sizes, and the more info we have the better we can fix it.

**Comment by zackkrida** [comment]
When viewing a list of translation strings like https://translate.wordpress.org/projects/wp/dev/dsb/default/?page=4, each translation has its own sticky header and menu:

![CleanShot 2022-01-24 at 18 43 58@2x](https://user-images.githubusercontent.com/6351754/150883853-0dcb6456-7c63-40fc-8690-49946540550d.png)

These can be obscured by the sticky header, which is particularly frustrating on short (namely small laptop and ultrabook) displays:

> before
![CleanShot 2022-01-24 at 18 49 17@2x](https://user-images.githubusercontent.com/6351754/150884336-e087ceb2-d90d-4c7c-b579-4a17017a969e.png)

> after
![CleanShot 2022-01-24 at 18 49 01@2x](https://user-images.githubusercontent.com/6351754/150884341-4eb3ec19-b7db-4e79-9f7b-e542487d9ced.png)

**Comment by iandunn** [comment]
I created #124 for the sticky element bug. 

Closing this since the work that it tracked is done.

**Comment by iandunn** [comment]
Some other Translate bugs were fixed in https://meta.trac.wordpress.org/ticket/6037 and https://meta.trac.wordpress.org/ticket/6046
