### ISSUE TITLE
Port old `header.php` features etc

### ISSUE THREAD

**Issue by iandunn** [WordPress/wporg-mu-plugins#42]
port any needed "features" from old header

### `header.php`

- [x] skip to content links. maybe adjust to use [block theme standard](https://github.com/WordPress/gutenberg/blob/trunk/docs/how-to-guides/themes/block-theme-overview.md#accessibility). remove duplicate markup in themes that adds it (e.g., `wporg-learn-2020/header.php`).
- [x] ~`content-type` header?~ Taken care of by `WP::send_headers()`
- [x] `no-index` when accessed directly?
- [ ] ~text direction~ No, i18n menu, other i18n features
- [x] `<meta>` tags - do via hook so it affects classic and FSE
  - [x] `<meta name="viewport">`
  - [x] ~`<meta name="referrer" content="always">`~ Invalid Header.
  - [x] `<meta charset="utf-8" />`
- [x] `<link>` tags - do via hook so it affects classic and FSE
  - [x] `<link rel="shortcut icon">`
- [x] `<script>` tags - do via hook so it affects classic and FSE
  - [x] `body.no-js` => `body.js`
  - [x] ~Googletagmanager~ Handled in plugin.
  - [x] ~Always enqueue jQuery. Needed anywhere??~ No.
- [x] `<style>` tags - do via hook so it affects classic and FSE
  - [x] ~Survey Banner~ #93
- [x] codex-specific stuff?
- [x] `<body id="wordpress-org"` - is this needed? might be hacky to add to FSE body, so maybe port to class or something?
- [x] ~annual survey - it'd be nice to do this in a cleaner way, and maybe use native localization instead of hardcoding~ #93
- [x] header "options" like title , wrapper items, `$headadd`, etc. there may be a cleaner way to do it
  - [x] `$pagetitle` global in Themes, Rosetta, GlotPress.
  - [x] `$pagetitle` global in Planet
  - [x] `$headadd`
  - [x] `$wporg_global_header_options` (sans #93)
- [x] download mobile
- [x] google analytics
- [x] ~`X-Olaf`~ No.
- [x] ~rosetta `get_header_announcements()` ?~ #93
- [x] anything else from `load_custom_header()`?  (because it's no longer used)

### `functions-global.php`
- [x] capital P - is this for menu items that rosetta/etc admins create? might be cleaner to filter `wp_get_nav_menu_items()` or whatever, rather than buffering in this file
- [x] 301 redirect - still needed?
- [x] menu generation not needed anymore?
- [x] maybe port some of the localization stuff, but in a cleaner way
- [x] anything else?

**Comment by dd32** [comment]
> skip to content links.

Looking for other uses of the skip-to link in our themes shows that a number of themes have a variant on it, and some don't even place the skip link at the start of the document (developer.w.org for example is between the header and the content that it then skips to)

Temporarily handled that via https://github.com/WordPress/wordpress.org/commit/ab3eed116dde78c45620e66cf88e028db7cac2e1

We'll still need to handle that with the other `header "options" ` stuff.

>  text direction

New header takes care of those already.

> download mobile

https://github.com/WordPress/wordpress.org/commit/e9708fa487cbff6fc60037c3f560f83e197d54c6

>  google analytics

Taken care of via https://meta.trac.wordpress.org/browser/sites/trunk/wordpress.org/public_html/wp-content/mu-plugins/pub/wporg-google-tag-manager.php

> X-Olaf

Olaf he shall; It's time for him to retire from WordPress.org

> `<body id="wordpress-org"` - is this needed?

Looks like it's being used in the Gutenberg theme as a super hard-level heading override selector:
https://github.com/WordPress/wordpress.org/blob/trunk/wordpress.org/public_html/wp-content/themes/pub/gutenberg/style.css#L1102-L1114

Can't find it in Codex.

Also used by the subscription widget: https://github.com/WordPress/wordpress.org/commit/35309f618e9370352d5e1abda63f140cdc41eb5a#diff-359f1279063b3388ff9cc37db057279e2cb4c5e96b7950d15a75381466aea6d4R1879-R1885

We can remove that ID.

**Comment by dd32** [comment]
**functions-global.php**
> capital P - is this for menu items that rosetta/etc admins create? might be cleaner to filter wp_get_nav_menu_items() or whatever, rather than buffering in this file

That predates a lot of things, IIRC it might be related to forum data? I think we should just remove it and fix it elsewhere when it comes up by hooking the proper function within WordPress.

> 301 redirect - still needed?

The catch-all hostname one can probably go.. It's handled either by nginx or Multisite network-not-found/site-not-found.

The index.php one will need to remain in some form, probably moved to the other canonical ruleset on dotorg.

> menu generation not needed anymore?

Sounds right to me. 

> maybe port some of the localization stuff, but in a cleaner way

The `fetch-custom-header` stuff in there is for bbPress 1.x use of the header on localised sites, of which there should be none anymore. That should be ditchable.

**Comment by dd32** [comment]
>  codex-specific stuff?

There's a few placeholders we need to output in the appropriate places for MediaWiki: `<!-- [codex head html] -->`, `<!-- [codex head meta] -->`, `<!-- [codex head scripts] -->`

We need to ensure that this style is loaded: `<link rel="stylesheet" href="//s.w.org/style/codex-wp4.css?3" />`.

There's also a `// Opt codex into responsive styling.` function which can be removed, the responsive styles it enables really don't do much anymore.

I'll test how the Codex will function with the new header & footer next week (I have a test environment for it).

**Comment by dd32** [comment]
>  $pagetitle global in Themes, Rosetta, GlotPress.

The majority of that has been taken care of via: https://github.com/WordPress/wordpress.org/commit/8caf64970c82d7b28e942121cf93952ba31f8802 https://github.com/WordPress/wordpress.org/commit/3f5740fae06205615c31583b042da4d4ff2c4224 https://github.com/WordPress/wordpress.org/commit/407e0b3dd999345da6b1e989966b954226bd3a4f

**Comment by dd32** [comment]
I'm calling this issue almost done. header.php is starting to look rather bland.

>  capital P - is this for menu items that rosetta/etc admins create? might be cleaner to filter wp_get_nav_menu_items() or whatever, rather than buffering in this file

I think we can probably remove this global filter and attach the WP variant to the `the_content` and `comment_text` filters instead on all sites with UGC instead. The buffer filter was mostly to catch UGC (Forum posts, Plugin & Theme descriptions, etc), I suspect it was done as a output buffer purely to catch all the various apps that were running on dotorg.

**Comment by dd32** [comment]
> I think we can probably remove this global filter and attach the WP variant to the `the_content` and `comment_text` filters

In core, it's applied to...`'the_content', 'the_title', 'wp_title', 'document_title', 'comment_text', 'widget_text_content'`.

In bbPress, it's additionally applied to `'bbp_get_reply_content', 'bbp_get_topic_content'`.

On developer.w.org, it's specifically removed from `comment_text`.
On translate.w.org, it's applied to saved translations.

I think it's safe to disable. Done in r18322-dotorg.
