### ISSUE TITLE
Post launch tasks

### ISSUE THREAD

**Issue by iandunn** [WordPress/wporg-mu-plugins#55]
#38 has all the pre-launch tasks for rolling the new header/footer out to all sites in the w.org network. This issue tracks the post-launch tasks.

- [ ] port documentation from old `header.php` and `footer.php`
- [ ] delete unnecessary functions like `wporg_get_global_header()` and vars like `$wporg_global_header_options`
- [ ] delete old `/header.php` so it doesn't get used in future
- [ ] remove `wp-content/themes/pub/wporg/inc/header.php` since it's not used?
- [ ] remove old header/footer styles from `wp4.css` (and `-rtl`)
- [x] remove unused rosetta menu things like `fetch_custom_header_data()` unless still used by old bbpress? probably remove `load_custom_header()` and maybe others. leave `wp_nav_menu_objects` since it's being used
- [x] remove `$download` from `Rosetta_Sites::wp_nav_menu_objects()`
- [x] remove GlotPress customizations `switch_theme_for_new_header()`
- [ ] add mu-plugins repo to Learn env so header/footer works there. then delete old header/footer `include` and `wporg_get_global_header()`
- [ ] add mu-plugins repo to 5ftF env so header/footer works there. then delete old header/footer `include` and `wporg_get_global_header()`
- [ ] remove `FEATURE_2021_GLOBAL_HEADER_FOOTER` feature flag
- [ ] remove `navigation.js` from classic themes b/c not used anymore?
